name: mountaincar-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - gym=0.26.2
  - numpy=1.23.5
  - matplotlib=3.10.0
  - pygame=2.1.0
  - pip
  - pip:
      - cloudpickle==3.1.1
      - gym-notices==0.0.8